# Generated by Django 4.2.3 on 2023-08-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=250)),
                ('Description', models.TextField()),
                ('Date_Posted', models.DateTimeField(auto_now_add=True)),
                ('Date_Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Notice',
            },
        ),
    ]
